//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.ContentOrder = new HashSet<ContentOrder>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<double> amountDiscount { get; set; }
        public Nullable<int> idPickUpPoint { get; set; }
        public Nullable<int> receiptCode { get; set; }
        public Nullable<int> deliveryTime { get; set; }
        public int idUser { get; set; }
        public int idStatusOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentOrder> ContentOrder { get; set; }
        public virtual PickUpPoint PickUpPoint { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual User User { get; set; }
    }
}
