//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ContentOrder = new HashSet<ContentOrder>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public byte[] image { get; set; }
        public string description { get; set; }
        public int idManufacturer { get; set; }
        public int price { get; set; }
        public Nullable<double> discount { get; set; }
        public int amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentOrder> ContentOrder { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
